Traceback (most recent call last):
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/administrator/micromamba/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import datacube

# dask
import dask
from dask.distributed import Client
from deafrica_tools.dask import create_local_dask_cluster # digital earth africa datacube package, which already includes Dask functionality.
# plotting
import graphviz
import seaborn as sns

# images
import matplotlib.pyplot as plt
import pandas as pd
from odc.ui import with_ui_cbk

# vector
import geopandas as gpd
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mdatacube[39;00m
[1;32m      3[0m [38;5;66;03m# dask[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mdask[39;00m

[0;31mModuleNotFoundError[0m: No module named 'datacube'

